default:
  image: "alpine:latest"

  before_script:
    - apk add -q python3 python3-dev py3-pip gcc musl-dev libxml2-dev libxslt-dev
    - pip3 install --break-system-packages -r requirements-dev.txt
    - python3 --version

stages:
  - Static Analysis
  - Test

black:
  stage: Static Analysis
  script:
  - black --check --config pyproject.toml .
  allow_failure: true

flake8:
  stage: Static Analysis
  script:
  - flake8
  allow_failure: true

isort:
  stage: Static Analysis
  script:
  - isort --profile black --filter-files -c --skip EnergyDataset/manipulateTraces/ .
  allow_failure: true

cffconvert:
  stage: Static Analysis
  script:
  - cffconvert --validate -i CITATION.cff
  allow_failure: true

execute:
  stage: Test
  script:
  - ./misc/test.sh

